### obtener todos los tipo_productos
GET http://localhost:3000/api/tipo_producto


### obtener un tipo_producto

@id=2

GET http://localhost:3000/api/tipo_producto/{{id}}


### crear un nuevo tipo_producto

POST http://localhost:3000/api/tipo_producto
Content-Type: application/json

{
  
  "descripcion": "prueba"
  
}


### modificar un tipo_producto
PUT http://localhost:3000/api/tipo_producto/{{id}}
Content-Type: application/json
{
  "descripcion":"no perecedero modificado"
}


### borrar un tipo_producto

### cambiar el id que se quiere eliminar

@id_eliminar=3

DELETE http://localhost:3000/api/tipo_productos/{{id_eliminar}}
